import g4p_controls.*;

int yPos = 10;
public void setup() {
  size(400, 240, JAVA2D);
  createGUI();
}

public void draw() {
  background(125, 125, 125);
}

// From the gui tab

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  optGroupState = new GToggleGroup();
  
  options = new GCheckbox[3];
  for (int i = 0; i < 3; i++) {
    options[i] = new GCheckbox(this, 10, yPos, width/2.0, yPos, "Select State " + i);
    yPos = yPos + 20;
    
    optGroupState.addControl(options[i]);
    options[i].setSelected(false); 
  }
}

// Variable declarations 
// autogenerated do not edit
GToggleGroup optGroupState; 
GCheckbox[] options; 
